[package]
name = "ferinth-example"
version = "1.0.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "Example for Ferinth"
publish = false

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
ferinth = { path = ".." }
thiserror = "1"
