[package]
name = "ferinth"
# The major version specifies which version of the Modrinth API this supports
version = "1.2.1"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "A simple library to use the Modrinth API in Rust projects"
repository = "https://github.com/theRookieCoder/ferinth"
homepage = "https://docs.rs/ferinth"
license = "MIT"
publish = ["crates-io"]
keywords = ["modrinth", "minecraft", "modding"]
categories = ["api-bindings", "asynchronous"]
exclude = [
	"example/*"
]

[dependencies]
reqwest = { version = "0", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0", features = ["serde"] }
bytes = "1"
