[package]
name = "ferinth"
# The major version specifies which version of the Modrinth API this supports
version = "2.0.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>", "4JX"]
description = "A simple library to use the Modrinth API in Rust projects"
repository = "https://github.com/theRookieCoder/ferinth"
license = "MIT"
publish = ["crates-io"]
keywords = ["modrinth", "minecraft", "modding"]
categories = ["api-bindings", "asynchronous"]
exclude = ["example/*"]

[dependencies]
reqwest = { version = "0", default-features = false, features = [
    "json",
    "rustls-tls",
] }
chrono = { version = "0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
lazy-regex = "2"
thiserror = "1"
bytes = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-test = "0"
